import "@/styles/globals.css"
import "@/styles/style.css"
import Header from "@/components/Header"
import { Josefin_Sans } from "next/font/google"
import ReservationProvider from "./_store/ReservationContext "



const Josefin = Josefin_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
})


export const metadata = {
  title: {
    template: '%s | The-Wild-Oasis',
    default: 'Welcome | The Wild Oasis',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body

        className={`${Josefin.className} bg-primary-950 text-primary-100 min-h-screen flex flex-col antialiased`}
      >

        <Header />


        <div className="flex-1 px-8 py-12 grid">
          <main className="max-w-7xl mx-auto w-full">
            <ReservationProvider>
              {children}
            </ReservationProvider>
          </main>
        </div>
      </body>
    </html >
  )
}


